### ISSUE TITLE
Add more CLI games

### ISSUE THREAD

**Issue by Seniru** [Seniru/cli-games#11]
As I've seen so far, there is only one game for this entire repository. It would be great if somebody can add more games to this.

Here are some suggestions

- Easy
  - [ ] Simon says game
  - [X] Tic-Tac-Toe
  - [x] Text adventures
- Medium
  - [x] Maze escape game
- Hard
  - [ ] Shooter game
  - [x] Snake game

**Comment by dnhuan** [comment]
#21 Added Tic Tac Toe

**Comment by Seniru** [comment]
Added Text adventures game. Enjoy!
Related #30

**Comment by Seniru** [comment]
Update: Added Simon says game to the list. Open for anybody who likes to contribute

**Comment by Seniru** [comment]
Dont close this issue!

**Comment by Seniru** [comment]
Added the **Snake Game** 🎉 🎉 

![image](https://user-images.githubusercontent.com/34127015/72981221-4c595100-3e02-11ea-88cf-a94d14aaadd3.png)
