### ISSUE TITLE
Showing letters

### ISSUE THREAD

**Issue by moxxiq** [Seniru/cli-games#53]
A letter which is being shown the first time may be hidden in a word. So we have to check this letter even if it is already shown at the beginning of the game
![Screenshot_20191021_194415](https://user-images.githubusercontent.com/20956813/67225250-8e59ac00-f43b-11e9-8702-772701fc4047.png)

- [x] fix js version
- [x] fix python version

**Comment by Seniru** [comment]
This issue would be fixed with #54 soon, Hang tight!

**Comment by Seniru** [comment]
Reopened this issue because hangman python version is not fixed yet. May closed by #56
