### ISSUE TITLE
Create a README for the landing page

### ISSUE THREAD

**Issue by Seniru** [Seniru/cli-games#55]
Since contributions to this project are growing faster, we have to add a README page to involve the community more and help them for some contents. 

Here are some ideas for things that should be in the README

- [ ] About this project
- [ ] How to install / Play?
- [ ] Contribution guidelines (a separate contribution guideline file would be better though)
- [ ] Other information

**Comment by saheelwagh** [comment]
I will take this 👍

**Comment by Seniru** [comment]
I m taking this issue. If anybody wants it, raise your hands 🙋
