### ISSUE TITLE
adding game choise file 

### ISSUE THREAD

**Issue by Toni500github** [Seniru/cli-games#75]
i have created a simple games.sh file so that you don't need to do `cd game` and exec the js/py file
requirements: you need to run anyways npm install and pip install -r requirements.txt where it's required (ask here if you want an install.sh file for doing it auto)
ps: where there are js and py files, i choose to run the python file but you can just replace it with `npm run play` (on TicTacToe you need to run instead `node tictactoe.js`)
it's on https://github.com/Toni500github/cli-games/blob/master/games.sh

pls don't judge, i don't program and i'm a newbie and i'm learning shell and C#, not python lol

**Comment by salif** [comment]
Thank you for the pull requests!

**Comment by Toni500github** [comment]
no problems and welcome back :)
