### ISSUE TITLE
The Hangman game need translations and new words

### ISSUE THREAD

**Issue by salif** [Seniru/cli-games#9]
Hello everyone, the [Hangman](https://github.com/salifm/cli-games/tree/master/Hangman) game need translations and words.

### Translate

If you want to translate the game to your language, copy [en-us.json](https://github.com/salifm/cli-games/blob/master/Hangman/words/en-us.json) file in [words](https://github.com/salifm/cli-games/tree/master/Hangman/words) directory and rename it to `[your-language].json`(e.g. `zh-hk.json`), then translate it and send pull request.

### Add words

If you want to add new words, choose language from [words](https://github.com/salifm/cli-games/tree/master/Hangman/words) directory, add words to "words" field and send pull request.

**Comment by Seniru** [comment]
So we need to add only programming related words?

**Comment by salif** [comment]
@Seniru You can add whatever words you want.

**Comment by Seniru** [comment]
OK

**Comment by valerybriz** [comment]
Added Spanish #15

**Comment by sbab** [comment]
Added Italian translation in #17. Happy Hacktoberfest!

**Comment by ghost** [comment]
I'll add a few more German words.

Edit: PR'd as #18

**Comment by dnhuan** [comment]
#19 Vietnamese! Happy Hacktoberfest

**Comment by jackelinenascimento** [comment]
Hi!
I will add a few more Portuguese words.

**Comment by rafacazal** [comment]
Hey! I'll add a few more Spanish words!

**Comment by Seniru** [comment]
🎆 Wow! We have lots of translations. Cheers!!!
